[project]
name = "connor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ffmpeg-python>=0.2.0",
    "pytelegrambotapi>=4.30.0",
    "python-dotenv>=1.2.1",
    "yt-dlp>=2026.1.29",
]
